AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for PledgePal AppSync Events API

Resources:
  EventsApi:
    Type: AWS::AppSync::Api
    Properties:
      Name: 'PledgePal'
      EventConfig:
        AuthProviders:
          - AuthType: API_KEY
        ConnectionAuthModes:
          - AuthType: API_KEY
        DefaultPublishAuthModes:
          - AuthType: API_KEY
        DefaultSubscribeAuthModes:
          - AuthType: API_KEY

  PledgesNamespace:
    Type: AWS::AppSync::ChannelNamespace
    Properties:
      ApiId: !GetAtt EventsApi.ApiId
      Name: pledges

  PledgetPalApiKey:
    Type: AWS::AppSync::ApiKey
    Properties:
      ApiId: !GetAtt EventsApi.ApiId

Outputs:
  Endpoint:
    Description: AppSync Events endpoint
    Value: !Sub 'https://${EventsApi.Dns.Http}/event'
  ApiKey:
    Description: AppSync API Key
    Value: !Sub EventsApi.ApiKey
